language: node_js
node_js: "stable"

before_script:
  - npm install -g gulp
script: gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
